name: Deploy backend

on: workflow_call

# ---
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Build backend
        run: echo Build backend with tests run

  deploy-stage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy backend to stage/review app
        run: echo Backend is being deployed