name: Deploy frontend

on: workflow_call

# ---
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build frontend
        run: echo Build backend with tests run

  deploy-stage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy frontend to stage/review app
        run: echo Backend is being deployed